// All hardcoded dashboard UI-chrome strings, one object, two keys per string
// (fr/en) — mirrors the same pattern BOT_STRINGS uses on the backend
// (backend/src/utils/language.js), just for the admin dashboard's own
// interface rather than the bot's WhatsApp replies.

// Bilingual labels for the property `type` enum. Top-level because THREE
// pages need them (properties, appointments, lead detail) — the appointment
// views were previously rendering the raw DB enum ("appartement") because
// this map was only reachable via dashboardStrings[lang].properties.
// Mirrors PROPERTY_TYPE_LABELS in backend/src/utils/language.js.
export const propertyTypeLabels = {
    fr: {
        chambre_salon: 'Chambre salon',
        appartement: 'Appartement',
        villa: 'Villa',
        terrain: 'Terrain',
        mini_villa: 'Mini-villa',
        appartement_meuble: 'Appartement meublé',
    },
    en: {
        chambre_salon: 'Single room',
        appartement: 'Apartment',
        villa: 'Villa',
        terrain: 'Land',
        mini_villa: 'Mini-villa',
        appartement_meuble: 'Furnished apartment',
    },
};

// Coarse part-of-day, shown when a lead gave a day but no exact clock time
// ("demain matin" -> "22 août 2026, matin").
export const timeOfDayLabels = {
    fr: { morning: 'matin', afternoon: 'après-midi', evening: 'soir' },
    en: { morning: 'morning', afternoon: 'afternoon', evening: 'evening' },
};

export const dashboardStrings = {
    fr: {
        layout: {
            navLeads: 'Leads',
            navProperties: 'Biens',
            navAppointments: 'Rendez-vous',
            logout: 'Déconnexion',
        },
        leadsOverview: {
            heading: 'Leads',
            subtitle: 'Toutes les personnes ayant contacté le bot WhatsApp',
            statTotal: 'Total des leads',
            statToday: "Nouveaux aujourd'hui",
            statWeek: 'Nouveaux cette semaine',
            all: 'Tous',
            searchPlaceholder: 'Rechercher par nom ou téléphone…',
            colName: 'Nom',
            colPhone: 'Téléphone',
            colLang: 'Langue',
            colStatus: 'Statut',
            statusUpdateError: 'Échec de la mise à jour du statut.',
            colFirstContact: 'Premier contact',
            colLastMessage: 'Dernier message',
            emptyTitle: 'Aucun lead pour le moment',
            emptyFilterHint: 'Essayez une autre recherche ou un autre filtre.',
            emptyDefaultHint: 'Les leads apparaissent ici dès que le bot les capture.',
            unknownName: 'Inconnu',
            countOf: 'sur',
            countLeads: 'leads',
            loadError: 'Échec du chargement des leads.',
        },
        leadDetail: {
            backLink: '← Tous les leads',
            saving: 'Enregistrement…',
            statusUpdateError: 'Échec de la mise à jour du statut.',
            conversation: 'Conversation',
            appointments: 'Rendez-vous',
            noMessages: 'Aucun message pour le moment.',
            noAppointments: 'Aucune demande de visite.',
            requested: 'Demandé :',
            firstContact: 'Premier contact',
            lastMessage: 'Dernier message',
            loading: 'Chargement…',
            notFound: 'Lead introuvable.',
            loadError: 'Échec du chargement du lead.',
            unknownName: 'Inconnu',
            replyPlaceholder: 'Écrire un message…',
            send: 'Envoyer',
            sending: 'Envoi…',
            sendError: "Échec de l'envoi du message.",
            notes: 'Notes',
            notesPlaceholder: 'Notez ici toute information utile sur ce client…',
            notesSaving: 'Enregistrement…',
            notesSaved: 'Enregistré',
            notesError: "Échec de l'enregistrement des notes.",
        },
        properties: {
            heading: 'Biens',
            loading: 'Chargement…',
            listingsCount: (n) => `${n} annonce${n === 1 ? '' : 's'}`,
            all: 'Tous',
            searchPlaceholder: 'Rechercher par quartier, ville ou description…',
            photosComingSoon: 'Photos à venir',
            uploadPhoto: 'Ajouter une photo',
            uploading: 'Envoi…',
            uploadError: "Échec de l'envoi. Réessayez.",
            deleteError: 'Échec de la suppression de la photo.',
            uploadVideo: 'Ajouter une vidéo',
            replaceVideo: 'Remplacer la vidéo',
            removeVideo: 'Supprimer la vidéo',
            videoUploadError: "Échec de l'envoi de la vidéo. Réessayez.",
            videoDeleteError: 'Échec de la suppression de la vidéo.',
            emptyFilter: 'Aucun bien pour ce filtre',
            loadError: 'Échec du chargement des biens.',
            bedroomsAbbrev: 'ch.',
            typeLabels: propertyTypeLabels.fr, // same object — one copy, three consumers
            addProperty: 'Ajouter un bien',
            addFieldCity: 'Ville',
            addFieldNeighbourhood: 'Quartier',
            addFieldType: 'Type',
            addFieldPrice: 'Prix (F CFA)',
            addFieldBedrooms: 'Chambres',
            addFieldDescription: 'Description',
            addSubmit: 'Créer',
            addCancel: 'Annuler',
            addSaving: 'Création…',
            addError: 'Échec de la création. Vérifiez les champs.',
            deleteProperty: 'Supprimer',
            deletePropertyTitle: 'Supprimer ce bien ?',
            deletePropertyWarning: 'Cette action est irréversible.',
            deletePropertyError: 'Échec de la suppression.',
            reservedForLabel: 'Réservé pour',
            reservedForPlaceholder: 'Nom ou description',
            statusUpdateError: 'Échec de la mise à jour du statut.',
            addFieldTransaction: 'Transaction',
            filterAllTransactions: 'Louer + Vendre',
        },
        appointments: {
            heading: 'Rendez-vous',
            subtitle: 'Demandes de visite collectées par le bot WhatsApp',
            colLead: 'Lead',
            colProperty: 'Bien',
            colRequested: 'Demandé',
            colStatus: 'Statut',
            colBooked: 'Réservé le',
            unknownName: 'Inconnu',
            all: 'Tous',
            searchPlaceholder: 'Rechercher par lead, téléphone ou lieu…',
            emptyTitle: 'Aucun rendez-vous pour le moment',
            emptyHint: 'Les demandes de visite apparaissent ici dès que le bot en réserve une.',
            emptyFilterHint: 'Essayez une autre recherche ou un autre filtre.',
            loadError: 'Échec du chargement des rendez-vous.',
            statusUpdateError: 'Échec de la mise à jour du statut.',
        },
        login: {
            productName: 'EXCELIA',
            subtitle: 'Tableau de bord admin',
            usernameLabel: "Nom d'utilisateur",
            usernamePlaceholder: "Votre nom d'utilisateur",
            passwordLabel: 'Mot de passe',
            passwordPlaceholder: 'Votre mot de passe',
            emptyCredentialsError: "Entrez votre nom d'utilisateur et votre mot de passe.",
            invalidCredentialsError: 'Nom d’utilisateur ou mot de passe invalide.',
            genericError: 'Impossible de contacter le serveur. Réessayez.',
            checking: 'Vérification…',
            signIn: 'Se connecter',
        },
    },
    en: {
        layout: {
            navLeads: 'Leads',
            navProperties: 'Properties',
            navAppointments: 'Appointments',
            logout: 'Log out',
        },
        leadsOverview: {
            heading: 'Leads',
            subtitle: 'Everyone who has contacted the WhatsApp bot',
            statTotal: 'Total leads',
            statToday: 'New today',
            statWeek: 'New this week',
            all: 'All',
            searchPlaceholder: 'Search by name or phone…',
            colName: 'Name',
            colPhone: 'Phone',
            colLang: 'Language',
            colStatus: 'Status',
            statusUpdateError: 'Failed to update status.',
            colFirstContact: 'First contact',
            colLastMessage: 'Last message',
            emptyTitle: 'No leads yet',
            emptyFilterHint: 'Try a different search or filter.',
            emptyDefaultHint: 'Leads appear here once the bot captures them.',
            unknownName: 'Unknown',
            countOf: 'of',
            countLeads: 'leads',
            loadError: 'Failed to load leads.',
        },
        leadDetail: {
            backLink: '← All leads',
            saving: 'Saving…',
            statusUpdateError: 'Failed to update status.',
            conversation: 'Conversation',
            appointments: 'Appointments',
            noMessages: 'No messages yet.',
            noAppointments: 'No viewing requests.',
            requested: 'Requested:',
            firstContact: 'First contact',
            lastMessage: 'Last message',
            loading: 'Loading…',
            notFound: 'Lead not found.',
            loadError: 'Failed to load lead.',
            unknownName: 'Unknown',
            replyPlaceholder: 'Write a message…',
            send: 'Send',
            sending: 'Sending…',
            sendError: 'Failed to send message.',
            notes: 'Notes',
            notesPlaceholder: 'Jot down anything useful about this customer…',
            notesSaving: 'Saving…',
            notesSaved: 'Saved',
            notesError: 'Failed to save notes.',
        },
        properties: {
            heading: 'Properties',
            loading: 'Loading…',
            listingsCount: (n) => `${n} listing${n === 1 ? '' : 's'}`,
            all: 'All',
            searchPlaceholder: 'Search by neighbourhood, city, or description…',
            photosComingSoon: 'Photos coming soon',
            uploadPhoto: 'Upload photo',
            uploading: 'Uploading…',
            uploadError: 'Upload failed. Try again.',
            deleteError: 'Failed to remove photo.',
            uploadVideo: 'Upload video',
            replaceVideo: 'Replace video',
            removeVideo: 'Remove video',
            videoUploadError: 'Video upload failed. Try again.',
            videoDeleteError: 'Failed to remove video.',
            emptyFilter: 'No properties for this filter',
            loadError: 'Failed to load properties.',
            bedroomsAbbrev: 'bd.',
            typeLabels: propertyTypeLabels.en, // same object — one copy, three consumers
            addProperty: 'Add property',
            addFieldCity: 'City',
            addFieldNeighbourhood: 'Neighbourhood',
            addFieldType: 'Type',
            addFieldPrice: 'Price (F CFA)',
            addFieldBedrooms: 'Bedrooms',
            addFieldDescription: 'Description',
            addSubmit: 'Create',
            addCancel: 'Cancel',
            addSaving: 'Creating…',
            addError: 'Failed to create. Check the fields.',
            deleteProperty: 'Delete',
            deletePropertyTitle: 'Delete this property?',
            deletePropertyWarning: 'This cannot be undone.',
            deletePropertyError: 'Failed to delete.',
            reservedForLabel: 'Reserved for',
            reservedForPlaceholder: 'Name or description',
            statusUpdateError: 'Failed to update status.',
            addFieldTransaction: 'Transaction',
            filterAllTransactions: 'Rent + Sale',
        },
        appointments: {
            heading: 'Appointments',
            subtitle: 'Viewing requests collected by the WhatsApp bot',
            colLead: 'Lead',
            colProperty: 'Property',
            colRequested: 'Requested',
            colStatus: 'Status',
            colBooked: 'Booked',
            unknownName: 'Unknown',
            all: 'All',
            searchPlaceholder: 'Search by lead, phone, or location…',
            emptyTitle: 'No appointments yet',
            emptyHint: 'Viewing requests appear here once the bot books one.',
            emptyFilterHint: 'Try a different search or filter.',
            loadError: 'Failed to load appointments.',
            statusUpdateError: 'Failed to update status.',
        },
        login: {
            productName: 'EXCELIA',
            subtitle: 'Admin dashboard',
            usernameLabel: 'Username',
            usernamePlaceholder: 'Your username',
            passwordLabel: 'Password',
            passwordPlaceholder: 'Your password',
            emptyCredentialsError: 'Enter your username and password.',
            invalidCredentialsError: 'Invalid username or password.',
            genericError: 'Could not reach the server. Please try again.',
            checking: 'Checking…',
            signIn: 'Sign in',
        },
    },
};

// timeAgo needs its own small translated table since it's a function of a
// live value (minutes/hours/days), not a static lookup.
export const formatTimeAgo = (date, lang) => {
    const seconds = Math.floor((new Date() - new Date(date)) / 1000);
    if (lang === 'fr') {
        if (seconds < 60) return "à l'instant";
        if (seconds < 3600) return `il y a ${Math.floor(seconds / 60)}min`;
        if (seconds < 86400) return `il y a ${Math.floor(seconds / 3600)}h`;
        return `il y a ${Math.floor(seconds / 86400)}j`;
    }
    if (seconds < 60) return 'Just now';
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    return `${Math.floor(seconds / 86400)}d ago`;
};
