// All hardcoded dashboard UI-chrome strings, one object, two keys per string
// (fr/en) — mirrors the same pattern BOT_STRINGS uses on the backend
// (backend/src/utils/language.js), just for the admin dashboard's own
// interface rather than the bot's WhatsApp replies.

export const dashboardStrings = {
    fr: {
        layout: {
            navLeads: 'Leads',
            navProperties: 'Biens',
            navAppointments: 'Rendez-vous',
            logout: 'Déconnexion',
        },
        leadsOverview: {
            heading: 'Leads',
            subtitle: 'Toutes les personnes ayant contacté le bot WhatsApp',
            statTotal: 'Total des leads',
            statToday: "Nouveaux aujourd'hui",
            statWeek: 'Nouveaux cette semaine',
            all: 'Tous',
            searchPlaceholder: 'Rechercher par nom ou téléphone…',
            colName: 'Nom',
            colPhone: 'Téléphone',
            colLang: 'Langue',
            colStatus: 'Statut',
            colFirstContact: 'Premier contact',
            colLastMessage: 'Dernier message',
            emptyTitle: 'Aucun lead pour le moment',
            emptyFilterHint: 'Essayez une autre recherche ou un autre filtre.',
            emptyDefaultHint: 'Les leads apparaissent ici dès que le bot les capture.',
            unknownName: 'Inconnu',
            countOf: 'sur',
            countLeads: 'leads',
            loadError: 'Échec du chargement des leads.',
        },
        leadDetail: {
            backLink: '← Tous les leads',
            saving: 'Enregistrement…',
            statusUpdateError: 'Échec de la mise à jour du statut.',
            conversation: 'Conversation',
            appointments: 'Rendez-vous',
            noMessages: 'Aucun message pour le moment.',
            noAppointments: 'Aucune demande de visite.',
            requested: 'Demandé :',
            firstContact: 'Premier contact',
            lastMessage: 'Dernier message',
            loading: 'Chargement…',
            notFound: 'Lead introuvable.',
            loadError: 'Échec du chargement du lead.',
            unknownName: 'Inconnu',
            replyPlaceholder: 'Écrire un message…',
            send: 'Envoyer',
            sending: 'Envoi…',
            sendError: "Échec de l'envoi du message.",
        },
        properties: {
            heading: 'Biens',
            loading: 'Chargement…',
            listingsCount: (n) => `${n} annonce${n === 1 ? '' : 's'}`,
            all: 'Tous',
            searchPlaceholder: 'Rechercher par quartier, ville ou description…',
            photosComingSoon: 'Photos à venir',
            uploadPhoto: 'Ajouter une photo',
            uploading: 'Envoi…',
            uploadError: "Échec de l'envoi. Réessayez.",
            deleteError: 'Échec de la suppression de la photo.',
            emptyFilter: 'Aucun bien pour ce filtre',
            loadError: 'Échec du chargement des biens.',
            bedroomsAbbrev: 'ch.',
            typeLabels: {
                chambre_salon: 'Chambre salon',
                appartement: 'Appartement',
                villa: 'Villa',
                terrain: 'Terrain',
                mini_villa: 'Mini-villa',
                appartement_meuble: 'Appartement meublé',
            },
        },
        appointments: {
            heading: 'Rendez-vous',
            subtitle: 'Demandes de visite collectées par le bot WhatsApp',
            colLead: 'Lead',
            colProperty: 'Bien',
            colRequested: 'Demandé',
            colStatus: 'Statut',
            colBooked: 'Réservé le',
            unknownName: 'Inconnu',
            searchPlaceholder: 'Rechercher par lead, téléphone ou lieu…',
            emptyTitle: 'Aucun rendez-vous pour le moment',
            emptyHint: 'Les demandes de visite apparaissent ici dès que le bot en réserve une.',
            emptyFilterHint: 'Essayez une autre recherche.',
            loadError: 'Échec du chargement des rendez-vous.',
        },
        login: {
            productName: 'EXCELIA',
            subtitle: 'Tableau de bord admin',
            usernameLabel: "Nom d'utilisateur",
            usernamePlaceholder: "Votre nom d'utilisateur",
            passwordLabel: 'Mot de passe',
            passwordPlaceholder: 'Votre mot de passe',
            emptyCredentialsError: "Entrez votre nom d'utilisateur et votre mot de passe.",
            invalidCredentialsError: 'Nom d’utilisateur ou mot de passe invalide.',
            genericError: 'Impossible de contacter le serveur. Réessayez.',
            checking: 'Vérification…',
            signIn: 'Se connecter',
        },
    },
    en: {
        layout: {
            navLeads: 'Leads',
            navProperties: 'Properties',
            navAppointments: 'Appointments',
            logout: 'Log out',
        },
        leadsOverview: {
            heading: 'Leads',
            subtitle: 'Everyone who has contacted the WhatsApp bot',
            statTotal: 'Total leads',
            statToday: 'New today',
            statWeek: 'New this week',
            all: 'All',
            searchPlaceholder: 'Search by name or phone…',
            colName: 'Name',
            colPhone: 'Phone',
            colLang: 'Lang',
            colStatus: 'Status',
            colFirstContact: 'First contact',
            colLastMessage: 'Last message',
            emptyTitle: 'No leads yet',
            emptyFilterHint: 'Try a different search or filter.',
            emptyDefaultHint: 'Leads appear here once the bot captures them.',
            unknownName: 'Unknown',
            countOf: 'of',
            countLeads: 'leads',
            loadError: 'Failed to load leads.',
        },
        leadDetail: {
            backLink: '← All leads',
            saving: 'Saving…',
            statusUpdateError: 'Failed to update status.',
            conversation: 'Conversation',
            appointments: 'Appointments',
            noMessages: 'No messages yet.',
            noAppointments: 'No viewing requests.',
            requested: 'Requested:',
            firstContact: 'First contact',
            lastMessage: 'Last message',
            loading: 'Loading…',
            notFound: 'Lead not found.',
            loadError: 'Failed to load lead.',
            unknownName: 'Unknown',
            replyPlaceholder: 'Write a message…',
            send: 'Send',
            sending: 'Sending…',
            sendError: 'Failed to send message.',
        },
        properties: {
            heading: 'Properties',
            loading: 'Loading…',
            listingsCount: (n) => `${n} listing${n === 1 ? '' : 's'}`,
            all: 'All',
            searchPlaceholder: 'Search by neighbourhood, city, or description…',
            photosComingSoon: 'Photos coming soon',
            uploadPhoto: 'Upload photo',
            uploading: 'Uploading…',
            uploadError: 'Upload failed. Try again.',
            deleteError: 'Failed to remove photo.',
            emptyFilter: 'No properties for this filter',
            loadError: 'Failed to load properties.',
            bedroomsAbbrev: 'bd.',
            typeLabels: {
                chambre_salon: 'Single room',
                appartement: 'Apartment',
                villa: 'Villa',
                terrain: 'Land',
                mini_villa: 'Mini-villa',
                appartement_meuble: 'Furnished apartment',
            },
        },
        appointments: {
            heading: 'Appointments',
            subtitle: 'Viewing requests collected by the WhatsApp bot',
            colLead: 'Lead',
            colProperty: 'Property',
            colRequested: 'Requested',
            colStatus: 'Status',
            colBooked: 'Booked',
            unknownName: 'Unknown',
            searchPlaceholder: 'Search by lead, phone, or location…',
            emptyTitle: 'No appointments yet',
            emptyHint: 'Viewing requests appear here once the bot books one.',
            emptyFilterHint: 'Try a different search.',
            loadError: 'Failed to load appointments.',
        },
        login: {
            productName: 'EXCELIA',
            subtitle: 'Admin dashboard',
            usernameLabel: 'Username',
            usernamePlaceholder: 'Your username',
            passwordLabel: 'Password',
            passwordPlaceholder: 'Your password',
            emptyCredentialsError: 'Enter your username and password.',
            invalidCredentialsError: 'Invalid username or password.',
            genericError: 'Could not reach the server. Please try again.',
            checking: 'Checking…',
            signIn: 'Sign in',
        },
    },
};

// timeAgo needs its own small translated table since it's a function of a
// live value (minutes/hours/days), not a static lookup.
export const formatTimeAgo = (date, lang) => {
    const seconds = Math.floor((new Date() - new Date(date)) / 1000);
    if (lang === 'fr') {
        if (seconds < 60) return "à l'instant";
        if (seconds < 3600) return `il y a ${Math.floor(seconds / 60)}min`;
        if (seconds < 86400) return `il y a ${Math.floor(seconds / 3600)}h`;
        return `il y a ${Math.floor(seconds / 86400)}j`;
    }
    if (seconds < 60) return 'Just now';
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    return `${Math.floor(seconds / 86400)}d ago`;
};
